### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './logs/2024-08-11 xx:xx:xx_netflix_lightgcn

### ISSUE THREAD

**Issue by LouHerGetUp** [HKUDS/LLMRec#22]
Hi! When I run 
```python ./main.py --dataset netflix```
The program reports the following error
```
n_users=13187, n_items=17366
n_interactions=70778
n_train=68933, n_test=1845, sparsity=0.00031
2024-08-11 16:56:  PID: 3356
Traceback (most recent call last):
  File "/root/LLMRec/./main.py", line 368, in <module>
    trainer = Trainer(data_config=config)
  File "/root/LLMRec/./main.py", line 42, in __init__
    self.logger.logging("PID: %d" % os.getpid())
  File "/root/LLMRec/utility/logging.py", line 13, in logging
    with open(os.path.join(os.path.join(self.path, self.filename)), 'a+') as f_log:
FileNotFoundError: [Errno 2] No such file or directory: './logs/2024-08-11 16:56:14_netflix_lightgcn'
```
Do you know what the problem is, please? How should I fix it? Please help, it is very important for me! Thank you very much!

**Comment by LouHerGetUp** [comment]
I'm stupid. Just create a new folder.

**Comment by zhangyida123456** [comment]
> 我很愚蠢。只需创建一个新文件夹。



> 我很愚蠢。只需创建一个新文件夹。
Hello, may I ask if the Netflix dataset you used is the raw dataset or the processed version from the authors? Sorry for the disturbance.

Best regards
